version: '2'

services:
  mssql:
    container_name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: NewYearNewMe9
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - test
networks:
  test:
    driver: bridge